### PR TITLE
Remove invalid `?` syntax from src

### LINKED ISSUE #128: Webpack compilation error
Whenever I try to run my Cypress tests on version `2.3.1`, I get the webpack compilation error described below. This has already been mentioned in [another issue](https://github.com/abhinaba-ghosh/cypress-react-selector/issues/123#issuecomment-762385693), but I thought it best to create a separate issue for this exact bug.

```
yarn run v1.22.4
$ C:\Users\toblo\Code\vms\node_modules\.bin\cypress run --headless --quiet --record false

Couldn't find tsconfig.json. tsconfig-paths will be skipped

Oops...we found an error preparing this test file:

  cypress\support\index.js

The error was:

Error: Webpack Compilation Error
./node_modules/cypress-react-selector/src/reactHandler.js 124:62
Module parse failed: Unexpected token (124:62)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|             value = Cypress.$(value);
|           }
>           return cy.verifyUpcomingAssertions(value, reactOpts?.options, {
|             onRetry: resolveValue,
|           });
 @ ./node_modules/cypress-react-selector/index.js 8:4-33
 @ ./cypress/support/index.js

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

This seems to be caused by the question mark, which is invalid JS syntax. Perhaps some TypeScript isn't being compiled on release or something? The same happens on line 238, as well as twice on line 73 of `utils.js`. I did a test where I replaced the question mark with something like this `(reactOpts || {}).options` and everything seemed to work.

Downgrading to `2.2.2` also fixed the issue.

### PR DESCRIPTION
**Pull request by tobloef**
Fixes #128

You may have some other fix in mind, feel free to close this PR in that case.

### CODE REVIEW

File: src/reactHandler.js [hunk 1]
```diff
@@ -121,7 +121,7 @@ exports.react = (subject, component, reactOpts = {}) => {
           if (!isPrimitive(value)) {
             value = Cypress.$(value);
           }
-          return cy.verifyUpcomingAssertions(value, reactOpts?.options, {
+          return cy.verifyUpcomingAssertions(value, (reactOpts || {}).options, {
```
Comment (abhinaba-ghosh) [inline src/reactHandler.js:124]: This opens up the chance to pass undefined `options` ({}.options -> undefined). We can also initialize it from the input parameter itself. 

```js
react(subject, component, reactOpts = { options:{}})
```
Then, perform operations as it is:

```js
   return cy.verifyUpcomingAssertions(value, (reactOpts.options, { ....
```

Can you try this one?

Comment (tobloef) [reply src/reactHandler.js:124]: Is it a problem that we can pass undefined `options`? As far as I can see, Cypress handles this case fine: https://github.com/cypress-io/cypress/blob/4d76049d2c419d77968beafcdda45585744fc542/packages/driver/src/cy/assertions.js#L138

Comment (abhinaba-ghosh) [reply src/reactHandler.js:124]: I didn't know that. Thanks for the same. At the same time do you think, passing it from the parameters makes the code a little readable and less in-line validations?

Comment (abhinaba-ghosh) [reply src/reactHandler.js:124]: But, I think we can live with it for now. merging it.

Thanks

**Review by abhinaba-ghosh — APPROVED** [review]

File: src/reactHandler.js (hunk 1 above)
Comment (tobloef) [reply src/reactHandler.js:124]: I agree that doing it in the function definition is indeed more readable, but unfortunately, this will not catch `null` values. The default value (`reactOpts = { options: {} }`) is only used when the input parameter is `undefined`, not when it's `null`. What do you think of doing something like `reactOpts = reactOpts || {}` at the top of the function, to keep it in one place, instead of doing it every time we use `reactOpts`?

Comment (tobloef) [reply src/reactHandler.js:124]: Anyway, I see you merged it. Thanks!
